name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - run: npm install
    - run: npm run build
    - run: npm install -g surge
    - run: surge --domain unofficial-observablehq-compiler-demo.surge.sh
      env: 
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
